export const languageStore = {
	en: {
		languageType: 'EN',
		header: 'Enter the link and get the QR',
		buttonTitleGetUserLink: 'Get QR',
		buttonTitleDownLoadPNG: 'Download in PNG',
		buttonTitleDownLoadSVG: 'Download in SVG',
		buttonTitleShareQR: 'Share QR',
		buttonTitleDeleteImage: 'Delete logo',
		buttonTitleAddLogoToQR: 'Add Logo to QR',
		titleSettingsQR: 'QR Settings',
		titleSettingsImage: 'Logo Settings',
		titleSettingsImageUpload: 'Uploading the logo to QR',
		titleSettingsImageUploadSub: 'It\'ll become available after adding the logo.',
		titleBriefHistory: 'Brief history',
		titleContacts: 'Author\'s Telegram',
		labelBackgroundColor: 'Background Color',
		labelCodeColor: 'Code Color',
		labelQRSizeSlider: 'QR Size',
		labelCheckbox: 'Remove the code under the picture',
		labelSelect: 'QR Quality',
		labelImageUpload: 'Insert a direct link to the logo',
		labelImageUploadFormat: 'Direct link ends in .jpeg .jpg .png .gif .webp .svg',
		valueSelectH: 'High',
		valueSelectQ: 'Above Average',
		valueSelectM: 'Medium',
		valueSelectL: 'Low',
		sliderImageOpacity: 'Logo opacity',
		sliderImageSize: 'Logo size',
		figcaptionFirstP: 'Viewing the uploaded logo',
		figcaptionSecondP: 'The logo displaying speed depends on the internet connection',
		placeholderInput: 'https://www.example.com',
		placeholderInputImageToQr: 'https://example.com/images/photo.jpg',
		paragraphHistoryFirst: 'QR — (abbreviation from Quick Response) was invented in 1994 by Japanese engineer Masahiro Hara from Denso Wave for labeling automotive parts, the code was developed under the influence of black and white chips played on the Go board (goban, 碁盤, Japanese).',
		paragraphHistorySecond: 'The location markers were determined by finding the least used sequence of alternating black and white areas on the printed product. The QR code shows black squares on a white background with orientation markers, which are read by cameras and processed using Reed-Solomon error correction until the image is interpreted appropriately.',
		paragraphHistoryThird: 'The initial application of QR codes was to simplify the tracking of types and quantities of automotive parts by replacing the individually scanned barcode labels on each auto parts box with a single label containing the data of each label.',
		companyName: 'Kravtsov Web Solutions',
	},
	ru: {
		languageType: 'RU',
		header: 'Введите ссылку и получите QR',
		buttonTitleGetUserLink: 'Получить QR',
		buttonTitleDownLoadPNG: 'Скачать в PNG',
		buttonTitleDownLoadSVG: 'Скачать в SVG',
		buttonTitleShareQR: 'Поделиться QR',
		buttonTitleDeleteImage: 'Удалить лого',
		buttonTitleAddLogoToQR: 'Добавить лого на QR',
		titleSettingsQR: 'Настройки QR',
		titleSettingsImage: 'Настройки лого',
		titleSettingsImageUpload: 'Загрузка лого на QR',
		titleSettingsImageUploadSub: 'Cтанут доступны после добавления лого',
		titleBriefHistory: 'Краткая история',
		titleContacts: 'Телеграм автора',
		labelBackgroundColor: 'Цвет фона',
		labelCodeColor: 'Цвет кода',
		labelQRSizeSlider: 'Размер QR',
		labelCheckbox: 'Удалить код под картинкой',
		labelSelect: 'Качество QR',
		labelImageUpload: 'Вставьте прямую ссылку на лого',
		labelImageUploadFormat: 'Прямая ссылка заканчивается на .jpeg .jpg .png .gif .webp .svg',
		valueSelectH: 'Высокое',
		valueSelectQ: 'Выше среднего',
		valueSelectM: 'Среднее',
		valueSelectL: 'Низкое',
		sliderImageOpacity: 'Прозрачность лого',
		sliderImageSize: 'Размер лого',
		figcaptionFirstP: 'Просмотр загруженного лого',
		figcaptionSecondP: 'Скорость отображения зависит от интернет соединения',
		placeholderInput: 'https://www.пример.рф',
		placeholderInputImageToQr: 'https://пример.рф/изображения/фото.jpg',
		paragraphHistoryFirst: 'QR — (аббревиатура от англ. Quick Response) — расшифровывается как «быстрый ответ» или «быстрое реагирование», был изобретён в 1994 году японским инженером Масахиро Хара из компании Denso Wave для маркировки автомобильных деталей, код был разработан под влиянием чёрных и белых фишек, которыми играли на доске в Go (goban, 碁盤, Японский).',
		paragraphHistorySecond: 'Расположение маркеров для определения местоположения было определено путем нахождения наименее используемой последовательности чередующихся черно-белых областей на печатной продукции. На QR-коде изображены чёрные квадраты на белом фоне с ориентировочными маркерами, которые считываются камерами и обрабатываются с помощью коррекции ошибок Рида–Соломона до тех пор, пока изображение не будет соответствующим образом интерпретировано.',
		paragraphHistoryThird: 'Первоначальное применение QR-кодов состояло в упрощении отслеживания типов и количества автомобильных деталей путем замены индивидуально отсканированных этикеток со штрих-кодом на каждой коробке автозапчастей на одну этикетку, содержащую данные каждой этикетки.',
		companyName: 'Кравцов Web решения',
	},
};
